package com.hank.musicfree.data.backup

import java.io.BufferedInputStream
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.OutputStream
import java.security.MessageDigest
import java.time.Instant
import java.time.format.DateTimeFormatter
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

class BackupArchiveWriter {
    private val requiredEntries = BackupArchivePaths.requiredEntries - BackupArchivePaths.MANIFEST

    fun writeArchive(
        outputFile: File,
        sourceFiles: List<BackupSourceFile>,
        metadata: BackupAppMetadata,
        databaseVersion: Int,
        createdAt: String = DateTimeFormatter.ISO_INSTANT.format(Instant.now()),
    ): BackupManifest {
        val validated = validate(sourceFiles)
        FileOutputStream(outputFile).use { fileOutput ->
            return writeValidated(
                output = fileOutput,
                files = validated,
                metadata = metadata,
                databaseVersion = databaseVersion,
                createdAt = createdAt,
            )
        }
    }

    fun write(
        output: OutputStream,
        files: List<BackupSourceFile>,
        metadata: BackupAppMetadata,
        databaseVersion: Int,
        createdAt: String = DateTimeFormatter.ISO_INSTANT.format(Instant.now()),
    ): BackupManifest {
        val validated = validate(files)

        return writeValidated(
            output = output,
            files = validated,
            metadata = metadata,
            databaseVersion = databaseVersion,
            createdAt = createdAt,
        )
    }

    private fun writeValidated(
        output: OutputStream,
        files: List<BackupSourceFile>,
        metadata: BackupAppMetadata,
        databaseVersion: Int,
        createdAt: String,
    ): BackupManifest {
        val validated = files
        val manifestEntries = ArrayList<BackupManifestFile>(validated.size)

        ZipOutputStream(output.buffered()).use { zip ->
            validated.forEach { sourceFile ->
                manifestEntries += writeDataEntry(zip, sourceFile)
            }
            return writeManifestEntry(
                zip = zip,
                manifestEntries = manifestEntries,
                metadata = metadata,
                databaseVersion = databaseVersion,
                createdAt = createdAt,
            )
        }
    }

    private fun validate(sourceFiles: List<BackupSourceFile>): List<BackupSourceFile> {
        if (sourceFiles.isEmpty()) {
            throw IllegalStateException("No backup source files provided")
        }

        val uniquePaths = HashSet<String>(sourceFiles.size)

        sourceFiles.forEach { source ->
            if (!BackupArchivePaths.isAllowedEntry(source.archivePath)) {
                throw IllegalArgumentException("Entry is not allowed in backup archive: ${source.archivePath}")
            }
            if (source.archivePath == BackupArchivePaths.MANIFEST) {
                throw IllegalArgumentException("Manifest must be generated by BackupArchiveWriter: ${source.archivePath}")
            }
            if (!uniquePaths.add(source.archivePath)) {
                throw IllegalStateException("Duplicate archive path: ${source.archivePath}")
            }
            if (!source.source.exists()) {
                throw IllegalStateException("Source file does not exist: ${source.source.path}")
            }
            if (!source.source.isFile) {
                throw IllegalStateException("Source is not a file: ${source.source.path}")
            }
        }

        val sourcePathSet = sourceFiles.associateBy { it.archivePath }
        val missingEntries = requiredEntries.filterNot { it in sourcePathSet }
        if (missingEntries.isNotEmpty()) {
            throw IllegalStateException("Missing required entries: ${missingEntries.joinToString()}")
        }

        val dbFile = sourcePathSet[BackupArchivePaths.DB]?.source
        if (dbFile == null || !dbFile.exists() || !dbFile.isFile) {
            throw IllegalStateException("Main database file is required and must exist: ${BackupArchivePaths.DB}")
        }

        return sourceFiles.sortedBy { it.archivePath }
    }

    private fun writeDataEntry(
        zip: ZipOutputStream,
        sourceFile: BackupSourceFile,
    ): BackupManifestFile {
        val digest = MessageDigest.getInstance("SHA-256")
        zip.putNextEntry(ZipEntry(sourceFile.archivePath))
        FileInputStream(sourceFile.source).use { input ->
            BufferedInputStream(input).use { buffered ->
                val size = copyToZip(
                    source = buffered,
                    destination = zip,
                    digest = digest,
                )
                zip.closeEntry()
                return BackupManifestFile(
                    path = sourceFile.archivePath,
                    sizeBytes = size,
                    sha256 = digest.digest().joinToString(separator = "") { "%02x".format(it) },
                )
            }
        }
    }

    private fun copyToZip(
        source: BufferedInputStream,
        destination: OutputStream,
        digest: MessageDigest,
    ): Long {
        var totalBytesRead = 0L
        val buffer = ByteArray(DEFAULT_BUFFER_SIZE)

        while (true) {
            val read = source.read(buffer)
            if (read < 0) break
            if (read > 0) {
                digest.update(buffer, 0, read)
                destination.write(buffer, 0, read)
                totalBytesRead += read.toLong()
            }
        }
        return totalBytesRead
    }

    private fun writeManifestEntry(
        zip: ZipOutputStream,
        manifestEntries: List<BackupManifestFile>,
        metadata: BackupAppMetadata,
        databaseVersion: Int,
        createdAt: String,
    ): BackupManifest {
        val manifest = BackupManifest(
            schemaVersion = BackupManifest.CURRENT_SCHEMA_VERSION,
            sourcePackageName = metadata.packageName,
            createdAt = createdAt,
            appVersionName = metadata.versionName,
            appVersionCode = metadata.versionCode,
            databaseVersion = databaseVersion,
            files = manifestEntries,
        )
        val bytes = Json.encodeToString(manifest).toByteArray(Charsets.UTF_8)
        val manifestEntry = ZipEntry(BackupArchivePaths.MANIFEST)
        zip.putNextEntry(manifestEntry)
        zip.write(bytes)
        zip.closeEntry()
        return manifest
    }
}
